config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'dashboard/index'
  end

  get '/admin', to: "admin/dashboard#index"
  # namespace :admin do
  #   resources :dashboard
  # end

  resources :material_requirements
  resources :plants do
    collection do 
      get :region_plants
      post :assign_plants
      post :remove_plants
      get :user_plants
    end
  end
  
  devise_scope :user do
      authenticated  do
        root to: 'visitors#index'
      end

      unauthenticated do
        root to: 'devise/sessions#new', as: 'unauthenticated_root'
      end
    end  


  # root to: 'visitors#index'
  devise_for :users
  
  resources :admin_users, :controller => 'users'
end

app/models/material_requirement.rb
class MaterialRequirement < ApplicationRecord
  belongs_to :plant
end

app/controllers/material_requirements_controller.rb
class MaterialRequirementsController < ApplicationController
  before_action :set_material_requirement, only: [:show, :edit, :update, :destroy]

  # GET /material_requirements
  # GET /material_requirements.json
  def index
    @material_requirements = MaterialRequirement.all
  end

  # GET /material_requirements/1
  # GET /material_requirements/1.json
  def show
  end

  # GET /material_requirements/new
  def new
    @material_requirement = MaterialRequirement.new
  end

  # GET /material_requirements/1/edit
  def edit
  end

  # POST /material_requirements
  # POST /material_requirements.json
  def create
    @material_requirement = MaterialRequirement.new(material_requirement_params)

    respond_to do |format|
      if @material_requirement.save
        format.html { redirect_to material_requirements_url, notice: 'Material requirement was successfully created.' }
        format.json { render :show, status: :created, location: @material_requirement }
      else
        format.html { render :new }
        format.json { render json: @material_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /material_requirements/1
  # PATCH/PUT /material_requirements/1.json
  def update
    respond_to do |format|
      if @material_requirement.update(material_requirement_params)
        format.html { redirect_to material_requirements_url, notice: 'Material requirement was successfully updated.' }
        format.json { render :show, status: :ok, location: @material_requirement }
      else
        format.html { render :edit }
        format.json { render json: @material_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /material_requirements/1
  # DELETE /material_requirements/1.json
  def destroy
    @material_requirement.destroy
    respond_to do |format|
      format.html { redirect_to material_requirements_url, notice: 'Material requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material_requirement
      @material_requirement = MaterialRequirement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_requirement_params
      params.require(:material_requirement).permit(:plant_id, :order_date, :item_code, :item_description, :item_type, :item_type_description, :uom, :demand, :receipts, :inv_on_hand, :inventory_run_out_time)
    end
end

app/helpers/material_requirements_helper.rb
module MaterialRequirementsHelper
end

app/views/material_requirements/_form.html.erb
<div class="row page-title">
  <div class="col-xs-6">
    <span class="title">Matirial Requirements - <%= material_requirement.persisted? ?  'Edit' : 'Add' %></span>
  </div>
  <div class="col-xs-12">
    <hr/>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(material_requirement) do |f| %>
      <% if material_requirement.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(material_requirement.errors.count, "error") %> prohibited this material_requirement from being saved:</h2>

          <ul>
          <% material_requirement.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :plant_id , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.select :plant_id, options_from_collection_for_select(Plant.active, :id, :plant_name, material_requirement.plant_id)%>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :order_date , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.date_select :order_date %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :item_code , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :item_code , class: 'form-control'%>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :item_description , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_area :item_description , class: 'form-control'%>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :item_type , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :item_type , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :item_type_description , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :item_type_description , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :uom , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :uom , class: 'form-control'%>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :demand , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :demand , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :receipts , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :receipts , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :inv_on_hand , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :inv_on_hand , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :inventory_run_out_time , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.datetime_select :inventory_run_out_time %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-xs-12">
          <div class="actions">
            <%= f.submit class: 'btn btn-success' %>
            <%= link_to 'Back', material_requirements_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/material_requirements/edit.html.erb
<%= render 'form', material_requirement: @material_requirement %>

app/views/material_requirements/index.html.erb
<div class="row page-title">
  <div class="col-xs-6">
    <span class="title">Matirial Requirements - List</span>
  </div>
  <div class="col-xs-6">
    <%= link_to 'New Requirement', new_material_requirement_path, class: 'btn btn-primary pull-right' %>
  </div>
  <div class="col-xs-12">
    <hr/>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Plant</th>
          <th>Order date</th>
          <th>Item code</th>
          <th>Item description</th>
          <th>Item type</th>
          <th>Item type description</th>
          <th>Uom</th>
          <th>Demand</th>
          <th>Receipts</th>
          <th>Inv on hand</th>
          <th>Inventory run out time</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @material_requirements.each do |material_requirement| %>
          <tr>
            <td><%= material_requirement.id %></td>
            <td><%= material_requirement.plant.plant_name %></td>
            <td><%= material_requirement.order_date %></td>
            <td><%= material_requirement.item_code %></td>
            <td><%= material_requirement.item_description %></td>
            <td><%= material_requirement.item_type %></td>
            <td><%= material_requirement.item_type_description %></td>
            <td><%= material_requirement.uom %></td>
            <td><%= material_requirement.demand %></td>
            <td><%= material_requirement.receipts %></td>
            <td><%= material_requirement.inv_on_hand %></td>
            <td><%= material_requirement.inventory_run_out_time %></td>
            <td>
              <%= link_to 'Edit', edit_material_requirement_path(material_requirement) %> | 
              <%= link_to 'Destroy', material_requirement, method: :delete, data: { confirm: 'Are you sure?' } %>    
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
 </div>
</div>

app/views/material_requirements/new.html.erb
<%= render 'form', material_requirement: @material_requirement %>

app/views/material_requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plant:</strong>
  <%= @material_requirement.plant.plant_name %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @material_requirement.order_date %>
</p>

<p>
  <strong>Item code:</strong>
  <%= @material_requirement.item_code %>
</p>

<p>
  <strong>Item description:</strong>
  <%= @material_requirement.item_description %>
</p>

<p>
  <strong>Item type:</strong>
  <%= @material_requirement.item_type %>
</p>

<p>
  <strong>Item type description:</strong>
  <%= @material_requirement.item_type_description %>
</p>

<p>
  <strong>Uom:</strong>
  <%= @material_requirement.uom %>
</p>

<p>
  <strong>Demand:</strong>
  <%= @material_requirement.demand %>
</p>

<p>
  <strong>Receipts:</strong>
  <%= @material_requirement.receipts %>
</p>

<p>
  <strong>Inv on hand:</strong>
  <%= @material_requirement.inv_on_hand %>
</p>

<p>
  <strong>Inventory run out time:</strong>
  <%= @material_requirement.inventory_run_out_time %>
</p>

<%= link_to 'Edit', edit_material_requirement_path(@material_requirement) %> |
<%= link_to 'Back', material_requirements_path %>