config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'dashboard/index'
  end

  get '/admin', to: "admin/dashboard#index"
  # namespace :admin do
  #   resources :dashboard
  # end

  resources :material_requirements
  resources :plants do
    collection do 
      get :region_plants
      post :assign_plants
      post :remove_plants
      get :user_plants
    end
  end
  
  devise_scope :user do
      authenticated  do
        root to: 'visitors#index'
      end

      unauthenticated do
        root to: 'devise/sessions#new', as: 'unauthenticated_root'
      end
    end  


  # root to: 'visitors#index'
  devise_for :users
  
  resources :admin_users, :controller => 'users'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :plants
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :filter_password, only: [:update]
  before_action :check_admin
  def index
    @users = User.all
  end

  def show
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :effective_start_date, :effective_end_date, :admin)
    end

    # Remove password field if it is empty so that devise should not give an error
    def filter_password
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
    end

    def check_admin
      unless current_user.admin?
        redirect_to :back, :alert => "Access denied."
      end
    end
end

app/views/users/_form.html.erb
<div class="row page-title">
  <div class="col-xs-6">
    <span class="title">Users - <%= user.persisted? ?  'Edit' : 'Add' %></span>
  </div>
  <div class="col-xs-12">
    <hr/>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(user, url: user.persisted? ?  admin_user_path(user) : admin_users_path) do |f| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :name , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :name , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :email , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.email_field :email , class: 'form-control'%>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :effective_start_date , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.date_select :effective_start_date , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :effective_end_date , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.date_select :effective_end_date , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :password , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :password , class: 'form-control'%>
          <% if user.persisted? %>
          <span class="help-text">leave the password field empty if you don't want to update password!</span>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :amin , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.check_box :admin %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-xs-12">
          <div class="actions">
            <%= f.submit class: 'btn btn-success' %>
            <%= link_to 'Back', admin_users_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<td><%= user.id%></td>
<td><%= link_to user.name, edit_admin_user_path(user) %></td>
<td><%= user.email %></td>
<td><%= user.effective_start_date %></td>
<td><%= user.effective_end_date %></td>
<td>
	<%= link_to 'Edit', edit_admin_user_path(user) %> |
	<%= link_to 'Delete', admin_user_path(user), method: :delete, data: {confirm: 'Are you sure you want to delete this user?'}%>
	
</td>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="row page-title">
  <div class="col-xs-6">
    <span class="title">Users - List</span>
  </div>
  <div class="col-xs-6">
    <%= link_to 'New User', new_admin_user_path, class: 'btn btn-primary pull-right' %>
  </div>
  <div class="col-xs-12">
    <hr/>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <table class="table table-hover">
      <thead>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
        <th>Effective Start Date</th>
        <th>Effective End Date</th>
        <th>Actions</th>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <%= render user %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Effective Start Date: <%= @user.effective_start_date if @user.effective_start_date %></p>
<p>Effective End Date: <%= @user.effective_end_date if @user.effective_end_date %></p>
<p>Admin: <%= @user.admin %></p>
<p>Password: <%= @user.password %></p>