config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'dashboard/index'
  end

  get '/admin', to: "admin/dashboard#index"
  # namespace :admin do
  #   resources :dashboard
  # end

  resources :material_requirements
  resources :plants do
    collection do 
      get :region_plants
      post :assign_plants
      post :remove_plants
      get :user_plants
    end
  end
  
  devise_scope :user do
      authenticated  do
        root to: 'visitors#index'
      end

      unauthenticated do
        root to: 'devise/sessions#new', as: 'unauthenticated_root'
      end
    end  


  # root to: 'visitors#index'
  devise_for :users
  
  resources :admin_users, :controller => 'users'
end

app/models/plant.rb
class Plant < ApplicationRecord

	has_and_belongs_to_many :users
	has_many :material_requirements

	scope :active, -> { where(active: true) }
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to plants_url, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to plants_url, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def region_plants
    # binding.pry
    if params[:user].blank?
      if params[:region]  == "Select Region"
        @plants= Plant.all      
      else
        @plants = Plant.where(region_name: params[:region])
      end
    elsif params[:region]  == "Select Region" and params[:user].present?
      plant_ids = User.find(params[:user]).plant_ids
      @plants = Plant.where.not(id: plant_ids)
    else
      plant_ids = User.find(params[:user]).plant_ids
      @plants = Plant.where.not(id: plant_ids).where(region_name: params[:region])

    end
    # if !params[:user].blank? and params[:region]  != "Select Region"
    #   @plant_ids = User.find(params[:user]).plant_ids
    #   binding.pry
    #   @plants = Plant.where.not(id: @plant_ids).where(region_name: params[:region])
    # elsif 
    #   @plants= Plant.all    
    # end
    # if params[:region]  == "Select Region"
    #   @plants= Plant.all      
    # else
    #   @plants = Plant.where(region_name: params[:region])
    # end
  end


  def assign_plants
    # binding.pry 
    @user = User.find(params[:user])

    if params[:plants].kind_of?(Array)
      @user.plants << Plant.find(params[:plants])
    else 
      !@user.plant_ids.include?(params[:plants].to_i)
      @user.plants << Plant.find(params[:plants])
    end
    
    @user_plants = @user.plants
    @plants = Plant.where.not(id: @user.plants.ids)
  end

  def remove_plants
    
    @user = User.find(params[:user])
    
    if params[:plants].kind_of?(Array)
      @user.plants.delete_all
    elsif !params[:plants]
      @user.plants.delete_all
    else
      @user.plant_ids.include?(params[:plants].to_i)
      @user.plants.delete(Plant.find(params[:plants]).id)
    end
    
    @user_plants = @user.plants
    @plants = Plant.where.not(id: @user.plants.ids)
  end

  def user_plants
    if params[:user].blank?
      if params[:region] == "Select Region"
        @plants = Plant.all
        @user_plants = []
      else
        @plants = Plant.where(region_name: params[:region])
        @user_plants = []
      end
    else
      @user = User.find(params[:user])
      @user_plants = @user.plants  
      @plants = Plant.where.not(id: @user.plants.ids)
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:region_name, :plant_code, :plant_name, :Active)
    end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.erb
<div class="row page-title">
  <div class="col-xs-6">
    <span class="title">Plants - <%= plant.persisted? ?  'Edit' : 'Add' %></span>
  </div>
  <div class="col-xs-12">
    <hr/>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(plant) do |f| %>
      <% if plant.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

          <ul>
          <% plant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :plant_name , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :plant_name , class: 'form-control'%>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :plant_code , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :plant_code , class: 'form-control'%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :region_name , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.text_field :region_name , class: 'form-control'%>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-md-3 col-xs-12 text-right">
          <%= f.label :Active , class: 'control-label'%>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= f.check_box :Active %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-xs-12">
          <div class="actions">
            <%= f.submit class: 'btn btn-success' %>
            <%= link_to 'Back', plants_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/plants/assign_plants.js.erb
$('.subject-info-box-1').html('<%=j select_tag "plants", options_from_collection_for_select(@plants, "id", "plant_name"),class: "form-control",multiple: true,id: "lstBox1" %>');


$('.subject-info-box-2').html('<%=j select_tag "plants", options_from_collection_for_select(@user_plants, "id", "plant_name"),class: "form-control",multiple: true,id: "lstBox1" %>');

app/views/plants/edit.html.erb
<%= render 'form', plant: @plant %>

app/views/plants/index.html.erb
<div class="row page-title">
  <div class="col-xs-6">
    <span class="title">Plants - List</span>
  </div>
  <div class="col-xs-6">
    <%= link_to 'New Plant', new_plant_path, class: 'btn btn-primary pull-right' %>
  </div>
  <div class="col-xs-12">
    <hr/>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Region name</th>
          <th>Plant code</th>
          <th>Plant name</th>
          <th>Active</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @plants.each do |plant| %>
          <tr>
            <td><%= plant.id %></td>
            <td><%= link_to plant.region_name, edit_plant_path(plant) %></td>
            <td><%= plant.plant_code %></td>
            <td><%= plant.plant_name %></td>
            <td><%= plant.Active %></td>
            <td>
              <%#= link_to 'Show', plant %>
              <%= link_to 'Edit', edit_plant_path(plant) %> |
              <%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/plants/new.html.erb
<%= render 'form', plant: @plant %>

app/views/plants/region_plants.js.erb
$('.subject-info-box-1').html('<%=j select_tag "plants", options_from_collection_for_select(@plants, "id", "plant_name"),class: "form-control",multiple: true,id: "lstBox1" %>');

app/views/plants/remove_plants.js.erb
$('.subject-info-box-1').html('<%=j select_tag "plants", options_from_collection_for_select(@plants, "id", "plant_name"),class: "form-control",multiple: true,id: "lstBox1" %>');


$('.subject-info-box-2').html('<%=j select_tag "plants", options_from_collection_for_select(@user_plants, "id", "plant_name"),class: "form-control",multiple: true,id: "lstBox1" %>');

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Region name:</strong>
  <%= @plant.region_name %>
</p>

<p>
  <strong>Plant code:</strong>
  <%= @plant.plant_code %>
</p>

<p>
  <strong>Plant name:</strong>
  <%= @plant.plant_name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @plant.Active %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/views/plants/user_plants.js.erb
$('.subject-info-box-2').html('<%=j select_tag "user_plants", options_from_collection_for_select(@user_plants, "id", "plant_name"),class: "form-control",multiple: true,id: "lstBox2" %>');

$('.subject-info-box-1').html('<%=j select_tag "plants", options_from_collection_for_select(@plants, "id", "plant_name"),class: "form-control",multiple: true,id: "lstBox1" %>');